# Generated by Django 2.2.19 on 2025-06-28 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diplom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(default=True, help_text='Введите навзвание образовательной организации', max_length=200, verbose_name='Название образовательной организации')),
                ('qualification', models.CharField(default=True, help_text='Напишите квалификацию', max_length=100, verbose_name='Квалификация')),
                ('ser_number', models.CharField(default=True, help_text='Введите номер серии', max_length=100, verbose_name='Номер серии')),
                ('reg_number', models.CharField(default=True, help_text='Введите регистрационный номер', max_length=10, verbose_name='Регистрационный номер')),
                ('grant_date', models.DateField(default=True, verbose_name='Дата выдачи')),
                ('student_name', models.CharField(default=True, help_text='ФИО', max_length=200, verbose_name='ФИО')),
                ('speciality', models.CharField(default=True, help_text='Введите специальность', max_length=100, verbose_name='Специальность')),
                ('supervisor', models.CharField(default=True, help_text='Введите ФИО руководителя', max_length=200, verbose_name='Руководитель')),
                ('chairman', models.CharField(default=True, help_text='Введите ФИО руководителя', max_length=200, verbose_name='Руководитель')),
                ('year', models.DateField(default=True, help_text='Введите дату решения', verbose_name='Дата решения')),
                ('copy', models.FileField(default=True, help_text='Вставьте копию диплома', upload_to='', verbose_name='Копия диплома')),
            ],
            options={
                'verbose_name': 'Диплом',
                'verbose_name_plural': 'Дипломы',
                'ordering': ('year',),
            },
        ),
    ]
