# Generated by Django 2.2.19 on 2025-06-27 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diplom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=200, verbose_name='Название образовательной организации')),
                ('qualification', models.CharField(max_length=100, verbose_name='Квалификация')),
                ('student_name', models.CharField(max_length=200, verbose_name='ФИО студента')),
                ('title', models.CharField(max_length=300, verbose_name='Название диплома')),
                ('supervisor', models.CharField(max_length=200, verbose_name='Руководитель')),
                ('year', models.DateField(verbose_name='Год защиты')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
        ),
    ]
