# Generated by Django 2.2.19 on 2025-06-27 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplom_spo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diplom',
            options={'ordering': ('year',), 'verbose_name': 'Диплом', 'verbose_name_plural': 'Дипломы'},
        ),
        migrations.RemoveField(
            model_name='diplom',
            name='description',
        ),
        migrations.AddField(
            model_name='diplom',
            name='complete',
            field=models.CharField(default=True, max_length=100, verbose_name='Осовил(а) образовательную программусреднего профессионального образования и успешнопрошёл(шла) государственную итоговую аттестациюпо специальности'),
        ),
        migrations.AddField(
            model_name='diplom',
            name='copy',
            field=models.FileField(default=True, upload_to='', verbose_name='Копия диплома'),
        ),
        migrations.AddField(
            model_name='diplom',
            name='grant_date',
            field=models.DateField(default=True, verbose_name='Дата выдачи'),
        ),
        migrations.AddField(
            model_name='diplom',
            name='reg_number',
            field=models.CharField(default=True, max_length=10, verbose_name='Регистрационный номер'),
        ),
        migrations.AddField(
            model_name='diplom',
            name='ser_number',
            field=models.IntegerField(default=True, verbose_name='Номер серии'),
        ),
        migrations.AlterField(
            model_name='diplom',
            name='org_name',
            field=models.CharField(default=True, max_length=200, verbose_name='Название образовательной организации'),
        ),
        migrations.AlterField(
            model_name='diplom',
            name='qualification',
            field=models.CharField(default=True, max_length=100, verbose_name='Квалификация'),
        ),
        migrations.AlterField(
            model_name='diplom',
            name='student_name',
            field=models.CharField(default=True, max_length=200, verbose_name='Настоящий дипломсвидетельствует о том, что'),
        ),
        migrations.AlterField(
            model_name='diplom',
            name='supervisor',
            field=models.CharField(default=True, max_length=200, verbose_name='Руководитель'),
        ),
        migrations.AlterField(
            model_name='diplom',
            name='title',
            field=models.CharField(default=True, max_length=300, verbose_name='Название диплома'),
        ),
        migrations.AlterField(
            model_name='diplom',
            name='year',
            field=models.DateField(default=True, verbose_name='Дата решения'),
        ),
    ]
